# Generated by Django 4.1 on 2024-09-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_seats_row_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
