# Generated by Django 4.1 on 2024-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rename_genre_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
